/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
/* tslint:disable */
export var styles = ['$bgColor[_ngcontent-%COMP%]:   lightcyan[_ngcontent-%COMP%];\nb[_ngcontent-%COMP%] {\n    background: $bgColor;\n}'];
